name: Continuous Integration

# This action works with pull requests and pushes
# This action works with ALL branches
on:
  push:
  pull_request:

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: ESLint
        run: npm run lint-total
      - name: Prettier
        run: npm run prettier-check
      - name: TypeScript Compiler
        run: npx tsc
        # Run Next Lint + TSC + BUILD
      - name: Next.js Build
        run: npm run build
